spring:
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: h2
  jackson:
    serialization:
      write-dates-as-timestamps: false