/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mmasayuki' at '16/08/05 23:30' with Gradle 2.14.1
 *
 * @author mmasayuki, @date 16/08/05 23:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
